version: '3.3'
services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogos
      MYSQL_PASSWORD: gogos
  
  gogs:
    image: gogs
    container_name: gogs
    restart: always
    ports:
      - 3000:3000
      - 3022:3022
    volumes:
      - ./gogs:/data
    links:
      - mysql