#filebeats.yml配置示例
filebeat.inputs:
- type: log
  enabled: true
  fields:
    appname: otc
  paths:
    - /opt/logs/otc/otc_uniform.log
  encoding: UTF-8
  multiline.pattern: ^\>
  multiline.negate: true
  multiline.match: after

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enable: false

output.logstash:
  hosts: ["192.168.9.172:5044"]
